### PR TITLE
Fix the_content link replacements

### LINKED ISSUE #2096: FaustWP - Content Replacement Bug
### Description

Here’s what we’re seeing with our current settings:
Current Case:
WordPress Settings:

General:
WordPress Address (URL): http://localhost:10005/
Site Address (URL): http://localhost:10005/

Media:
Full URL path to files: http://localhost:3000/wp-content/uploads

Faust:
Front-end site URL: http://localhost:3000/

Results:
srcset="http://localhost:3000http://localhost:3000/wp-content/uploads/2025/03/test-300x200.png 300w,...."
src="http://localhost:3000/wp-content/uploads/2025/03/test.png"

Case II:
WordPress Settings:

General:
WordPress Address (URL): http://localhost:10005/
Site Address (URL): http://localhost:10005/

Media:
Full URL path to files: (Removed, using default)

Faust:
Front-end site URL: http://localhost:3000/

Results:
srcset="http://localhost:3000/wp-content/uploads/2025/03/test-300x200.png 300w,...."
src="http://localhost:10005/wp-content/uploads/2025/03/test.png" 

Let me know if you need more details. 

### Steps to reproduce

Setup example site as described above

The srcset is adding 2 FE domains e.g. 

```
srcset="http://localhost:3000/wp-content/uploads/2025/03/test-300x200.png 300w,...."
src="http://localhost:10005/wp-content/uploads/2025/03/test.png" 
```

For context - 

```
Findings So Far:
The issue seems to stem from changes in image_source_srcset_replacement in Faust. Specifically, the function:

$relative_upload_url = faustwp_get_relative_upload_url( $wp_site_urls, wp_upload_dir()['baseurl'] );
Since $wp_site_urls and wp_upload_dir()['baseurl'] are different in our case, the function returns null, causing the condition:

strpos( $url, $relative_upload_url ) === 0
to evaluate incorrectly. This results in Faust incorrectly appending the frontend URL twice.
```

### Additional context

_No response_

### @faustwp/core Version

N/A

### @faustwp/cli Version

N/A

### FaustWP Plugin Version

1.8.0

### WordPress Version

6.7

### Additional environment details

_No response_

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### PR DESCRIPTION
**Pull request by alexwpengine**
## Tasks

- [x] I have signed a [Contributor License Agreement (CLA)](https://github.com/wpengine/faustjs#contributor-license-agreement) with WP Engine.
- [x] If a code change, I have written testing instructions that the whole team & outside contributors can understand.
- [x] I have written and included a comprehensive [changeset](https://github.com/wpengine/faustjs/blob/canary/DEVELOPMENT.md#deployment) to properly document the changes I've made.

## Description
Fix duplicate links and port not taken into account.
 * Replace the URLs in the post content basesd on two settings if enabled:
 1. Enable Post and Category URL rewrites - rewrite the WordPress internal URL in the content with the Front-end URL
1.1 If NOT enabled - use the WordPress URL
2. Use the WordPress domain for media URLs in post content - use WordPress URL for media files (images,csv,pdf)
2.1 If NOT enabled - use front-end url
## Related Issue(s):

Provide the GitHub issue(s) number for issue tracking purposes, use the following syntax:

- #2096 
https://github.com/wpengine/faustjs/pull/2014

## Testing

Sample post with images, csv/pdf, an internal link. 

The expected result must be:
 1. Enable Post and Category URL rewrites - rewrite the WordPress internal URL in the content with the Front-end URL
1.1 If NOT enabled - use the WordPress URL
2. Use the WordPress domain for media URLs in post content - use WordPress URL for media files (images,csv,pdf)
2.1 If NOT enabled - use front-end url

### CODE REVIEW

**Comment by colinmurphy** [comment]
@alexwpengine 

I will try and have a look tomorrow at why those tests are failing.

**Comment by colinmurphy** [comment]
@alexwpengine @theodesp 

I believe the e2e issue is related to - https://github.com/wpengine/faustjs/pull/2089

File: plugins/faustwp/includes/replacement/callbacks.php [hunk 1]
```diff
@@ -50,16 +55,42 @@ function content_replacement( ?string $content ) {
...
+			$is_wp_url = array_filter( $wp_site_urls, fn( $base ) => strpos( $url, $base ) === 0 );
+			if ( ! $is_wp_url ) {
+				continue;
+			}
+
+			// get relative link.
+			$relative = str_replace( reset( $is_wp_url ), '', $url );
+			$updated  = 'href="' . $frontend_uri . $relative . '"';
+
+			$original = $href_links[0][ $i ];
```
Comment (colinmurphy) [inline plugins/faustwp/includes/replacement/callbacks.php]: @alexwpengine 

I think we should check that key exists before doing any string replace

**Review by colinmurphy — CHANGES_REQUESTED** [review]
@alexwpengine 

I fixed the e2e bug.

Can we also add tests for what this fixes too please. Thank you for fixing this but I think it would be useful to have new tests too which act as documentation too.

**Review by colinmurphy — APPROVED** [review]
@alexwpengine 

This PR looks great 🚀 🚀 🚀 

Thanks for adding in the tests and also for fixing the issues with ports ❤️

**Comment by colinmurphy** [comment]
@alexwpengine 

Can you also add a changeset for this too please.  You should be able to add one clicking on the link above but let me know if you need any help.

**Review by theodesp — APPROVED** [review]
