### PR TITLE
Fix: (#422) Use most recent post/page revision if exists

### LINKED ISSUE #422: Bug: Existing post/page previews do not pull the latest revision
Viewing previews of existing posts/pages do not pull the latest revision. Instead, they show the published post/page content

## Applicable Versions

- `@faustjs/core` version: 0.9.0
- `@faustjs/react` version: 0.9.0
- `@faustjs/next` version: 0.9.0
- WordPress version: N/A

## Steps To Reproduce

1. Go to an existing page/post in the WordPress admin
2. Make changes
3. View Preview

## The current behavior

Upon clicking preview on an existing post or page, the user is given the most recently published content

## The expected behavior

Upon clicking preview on an existing post or page, the user is then given the most recent changes, regardless of publish status

### PR DESCRIPTION
**Pull request by blakewilson**
This PR resolves #422.

We now check if any revisions exist for the post/page. If they do, that is the most recent preview data for an existing post/page. Otherwise, we display the data from the original post/page query (draft, or new post/page)

### CODE REVIEW

File: packages/react/src/client.ts [hunk 1]
```diff
@@ -16,6 +16,9 @@ import merge from 'lodash/merge';
 
 export interface Node {
   id?: string | null;
+  revisions: (arg0: { first: number }) => {
```
Comment (wjohnsto) [inline packages/react/src/client.ts:19]: I think we might want a `WithRevisions` interface or something similar to this:

```ts
export interface Node {
  id?: string | null;
}

export interface WithRevisions {
  revisions: (arg0: { first: number }) => {
    edges?: { node?: Node }[];
  };
}

export interface RequiredQuery {
  posts: (args?: {
    where?: {
      categoryId?: number;
      categoryName?: string;
    };
  }) => unknown;
  post: (args: { id: string; idType?: PostIdType }) => (Node & WithRevisions) | null | undefined;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  pages: (args?: any) => unknown;
  page: (args: { id: string; idType?: PageIdType }) => (Node & WithRevisions) | null | undefined;
  category: (args: {
    id: string;
    idType?: CategoryIdType;
  }) => Node | null | undefined;
  generalSettings?: unknown;
}
```

Since `category` does not have `revisions`.

**Review by wjohnsto — CHANGES_REQUESTED** [review]

**Review by wjohnsto — APPROVED** [review]
