### PR TITLE
Bug: Fixed content replacment to allow null values

### LINKED ISSUE #2037: Content Replacment null values
### Description

There is a bug with FaustWP not allowing null values for the function callback `content_replacment` 

### Steps to reproduce

If you pass a null value for content_replacement, it will throw an error as the function expects a string.

### Additional context

_No response_

### @faustwp/core Version

N/A

### @faustwp/cli Version

N/A

### FaustWP Plugin Version

1.6.0

### WordPress Version

6.7

### Additional environment details

Issue caused by PR release #2014

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### PR DESCRIPTION
**Pull request by colinmurphy**
Fixes #2037 

## Tasks

- [x] I have signed a [Contributor License Agreement (CLA)](https://github.com/wpengine/faustjs#contributor-license-agreement) with WP Engine.
- [x] If a code change, I have written testing instructions that the whole team & outside contributors can understand.
- [x] I have written and included a comprehensive [changeset](https://github.com/wpengine/faustjs/blob/canary/DEVELOPMENT.md#deployment) to properly document the changes I've made.

## Description

Issue since 1.6.0 where by if you pass a null value for content_replacement it will throw a 500 error.

In 1.6.0 we changed the method signature for content_replacement from `content_replacement($content)` to `content_replacement( string $content)` which caused issues for anyone passing a null value for content replacement in Faust WP.

## Related Issue(s):

#2037 

## Testing

Tested locally with both single and multisite. 

## Screenshots

Testing content replacement on multisite.

image

## Documentation Changes

N/A

## Dependant PRs

N/A

### CODE REVIEW

File: plugins/faustwp/includes/replacement/callbacks.php [hunk 1]
```diff
@@ -27,44 +27,43 @@
...
  */
-function content_replacement( string $content ): string {
-
-	if ( ! $content ) {
-		return '';
-	}
-
-	$replace_content_urls = domain_replacement_enabled();
-	$replace_media_urls   = ! use_wp_domain_for_media();
+function content_replacement( $content ) {
```
Comment (theodesp) [inline plugins/faustwp/includes/replacement/callbacks.php]: Can't you just do `$content = ''`?

Comment (colinmurphy) [reply plugins/faustwp/includes/replacement/callbacks.php]: Updated. Thanks @theodesp for that suggestion.

File: plugins/faustwp/includes/replacement/callbacks.php [hunk 2]
```diff
@@ -31,36 +31,29 @@
  *
  * @return string The post content.
```
Comment (theodesp) [inline plugins/faustwp/includes/replacement/callbacks.php]: This needs to match the type of the `$content` type as defined in the: 

https://github.com/wpengine/wp-graphql-content-blocks/blob/8bd5bd40b2c9d5375ae01ddeb68b5dac9b57118a/includes/Data/ContentBlocksResolver.php#L57-L61

Comment (theodesp) [reply plugins/faustwp/includes/replacement/callbacks.php]:
```
* @param ?string                $content The content to parse.
```

Comment (colinmurphy) [reply plugins/faustwp/includes/replacement/callbacks.php]: Thanks @theodesp 

I pushed a fix for this.

**Review by theodesp — APPROVED** [review]

**Review by theodesp — APPROVED** [review]
