### PR TITLE
Preview Overhaul

### LINKED ISSUE #370: Preview Overhall
As discussed the other day. Preview handling needs a big overhaul to fix bugs and work better with various front-end frameworks. 

## New Features

- Don't require `/preview` prefix. Allow for doing previews based on the query params or custom prefix.
- Handle previews for published and draft content.
- Handle previews for custom post types or any other non-post/page content.
- ...

## Existing bugs
- When clicking page previews from editing the URL directs to the WP url and not localhost (aka headless url). Posts correctly directly to the headless app. THe "Preview" link available on the page list works, just not in the editing page.
- sometimes when following a preview link the `/preview` is after the page route, not before. 

## Todo
- [ ] Research needs to be done around WP previews and all the various ways it handles previews for different content types. 
- [ ] ...

## Related issues
https://github.com/WordPress/gutenberg/issues/33616#issuecomment-885056043

Let's use this topic to add any bugs, conversation, and research to work towards a new plan. Feel free to edit this original post to add things to the lists above.

### LINKED ISSUE #419: Bug: Existing post/page previews do not route correctly
Existing post/page previews do not route correctly due to the nature of their preview link structure including the post/page name in the URL:

```
# Existing post preview:
/hello-world/?preview_id=1&preview_nonce=3d6fd3a374&preview=true

# Existing page preview:
/sample-page/?preview_id=2&preview_nonce=6e61f798ea&preview=true
```

Opposed to new page/posts:

```
# New post preview:
/?p=6&preview=true

# New page preview:
/?page_id=9&preview=true

# Draft page preview:
/?page_id=3&preview=true
```

This can easily be fixed by implementing the Next.js redirects mentioned in #370.

## Applicable Versions

- `@faustjs/core` version: 0.8.0
- `@faustjs/react` version: 0.8.0
- `@faustjs/next` version: 0.8.0
- WordPress version: 5.8.0

## Steps To Reproduce

1. Navigate to a published page in WordPress
2. Modify page content
3. Click the "preview" button to navigate to the frontend

## The current behavior

When clicking the preview button for an existing post/page you are navigated to a page on the Faust.js frontend that does not correlate with the proper preview page, leading to a blank page.

## The expected behavior

When clicking the preview button for an existing page/post you are navigated to a page on the Faust.js frontend that demonstrates the latest revision

### PR DESCRIPTION
**Pull request by blakewilson**
This PR makes previews more consistent by using `redirects()` in the `next.config.js` to redirect all requests with a `preview` query param to the `/preview` page.

The `withFaust` function was introduced to enable users to merge their existing next config with the defaults set in Faust.

Additionally, we are now adding the preview link to the WP Admin edit post page via `wp_localize_script` so we can get the correct post preview link, and avoid the bug in new draft post/pages in https://github.com/WordPress/gutenberg/issues/13998

Resolves #370 
Resolves #419

### CODE REVIEW

File: packages/next/src/nextConfig.ts [hunk 1]
```diff
@@ -0,0 +1,26 @@
+import merge from 'lodash/merge';
+import { NextConfig } from 'next';
+
+export const defaultFaustNextConfig: NextConfig = {
```
Comment (wjohnsto) [inline packages/next/src/nextConfig.ts:4]: Maybe we want them to be able to send in an optional destination?

**Review by wjohnsto — CHANGES_REQUESTED** [review]

**Review by wjohnsto — APPROVED** [review]
