### PR TITLE
MERL-1228: Fix issue with rewriting links to front end

### LINKED ISSUE #1569: Bug: Replacement of media library URLs in post content
## Applicable Versions

- WordPress plugin version: 1.0.3
- WordPress version: 6.3.1

## Steps To Reproduce

1. Add a link in any post content to an item in the media library (e.g. a PDF for download)
2. Fetch the content using GraphQL and see that the media URL has been replaced with the frontend URL (which is normally not a valid URL).

## The current behavior

`includes/replacement/callbacks.php` is replacing any instance of the `site_url` using `the_content` filter.

## The expected behavior

It should only replace URLs that belong to permalinks, where it might be an internal link and should be handled by the frontend routing. Replacing media URLs will normally break those links.

I've also attempted a fix here to exclude the uploads directory from the replacements: https://github.com/clicksuite/faustjs/commit/cb6dcecfa05ea031e624da54b440440cc78a6860

Another option could be to look for file extensions with a regex similarly to the graphql URL replacement.

Can submit a PR for this if that would be useful!

### PR DESCRIPTION
**Pull request by mindctrl**
## Tasks

- [X] If a code change, I have written testing instructions that the whole team & outside contributors can understand.
- [x] I have written and included a comprehensive [changeset](https://github.com/wpengine/faustjs/blob/canary/DEVELOPMENT.md#deployment) to properly document the changes I've made.
- [x] phpunit tests added

## Description

Take two of https://github.com/wpengine/faustjs/pull/1603.
Adjusts the URL replacement logic to avoid rewriting links to files in the uploads dir.

## Related Issue(s):
- Closes #1569

## Testing

Bug is described here: https://github.com/wpengine/faustjs/issues/1569

See [this comment](https://github.com/wpengine/faustjs/pull/1624#issuecomment-1798569612) with info on demo data, queries, and results.

Ensure that links to posts, images, files, etc. are rewritten as expected. Try to break it!

### CODE REVIEW

File: plugins/faustwp/includes/replacement/callbacks.php [hunk 1]
```diff
@@ -27,26 +29,42 @@
  * @param string $content The post content.
  *
  * @return string The post content.
- * @todo Needs work...
  */
 function content_replacement( $content ) {
```
Comment (mindctrl) [inline plugins/faustwp/includes/replacement/callbacks.php:33]: This function now attempts to rewrites links in post_content once. Previously they were rewritten up to 3 times: 1) in `content_replacement` 2) in `image_source_replacement` 3) and in `url_replacement` for the GraphQL responses.

File: plugins/faustwp/includes/replacement/callbacks.php [hunk 2]
```diff
@@ -70,7 +88,6 @@ function image_source_replacement( $content ) {
 	return preg_replace( $patterns, "src=\"{$site_url}/", $content );
 }
 
-add_filter( 'wp_calculate_image_srcset', __NAMESPACE__ . '\\image_source_srcset_replacement' );
```
Comment (mindctrl) [inline plugins/faustwp/includes/replacement/callbacks.php:73]: Still testing this removal.

File: plugins/faustwp/includes/replacement/graphql-callbacks.php [hunk 3]
```diff
@@ -14,7 +14,6 @@
 	exit;
 }
 
-add_filter( 'graphql_request_results', __NAMESPACE__ . '\\url_replacement' );
```
Comment (mindctrl) [inline plugins/faustwp/includes/replacement/graphql-callbacks.php:17]: Also still testing this removal to ensure nothing broke. The tests pass, but we need to confirm we're not breaking things we're not testing.

File: plugins/faustwp/includes/settings/functions.php [hunk 4]
```diff
@@ -29,6 +29,15 @@ function is_rewrites_enabled() {
 	return '1' === faustwp_get_setting( 'enable_rewrites' );
 }
 
+/**
+ * Determines if posts and category URLs should link to the WP site.
+ *
+ * @return bool
+ */
+function use_wp_domain_for_post_and_category_urls() {
```
Comment (mindctrl) [inline plugins/faustwp/includes/settings/functions.php:37]: I introduced this function and `use_wp_domain_for_media` to make it easier to understand. Since Faust was rewriting content multiple times, the existing functions were a bit confusing IMO when reasoning about booleans. You had to know Faust rewrites multiple times to understand it.

**Comment by TeresaGobble** [comment]
Hi John, nice work on this! It's such a sneaky issue, I'm glad we have a fix in the works! ✨ 

I'm looking at canary now to see if I can understand what the issue is before testing- I added a couple of media links to a post and do not see them being rewritten to the front end:

Screenshot 2023-11-02 at 9 25 05 AM


If my frontend site url is localhost:3000, should I be seeing the youtube link and imgur links being rewritten to localhost:3000?

**Comment by mindctrl** [comment]
@TeresaGobble test for links to files in the media library in WP, as opposed to external URLs. Because of the bug we're fixing in #1625, it's trickier to test this one. I recommend temporarily deactivating the Faust plugin, creating some content that links to posts and media hosted on the WP site, save, and then reactivate Faust, and do your testing.

**Comment by TeresaGobble** [comment]
Hi @mindctrl! I have some testing results here to share- things are looking good! 

It seems like all the `src` links are being rewritten to localhost:3000. Below is the content from canary:

Screenshot 2023-11-02 at 4 07 21 PM

The items circled in blue are all the items that changed correctly upon switching to this PR's branch. 🎉 
I'm noticing we have a few image hrefs that remain the local site address for different dimensions of images, circled in red:

Screenshot 2023-11-02 at 4 16 21 PM

This is a hunch, but I think they refer to the aspect ratios in the block:
Screenshot 2023-11-02 at 4 40 37 PM

I also saw Theo and Blake examine the database directly in the Adminer on Local, and I'm noting all items are being written to the site domain, armadillo.local:

Screenshot 2023-11-02 at 4 45 30 PM

I'm wondering if it makes better sense for us to merge the other ticket, and then potentially retest this one with those changes?

**Comment by theodesp** [comment]
I'm seeing the following:

First I deactivated Faust:
I Then created a post with a pdf file, an image and an inline image.

I can see the following in the GraphQL Query which is correct. All media sources point to the WP URL.

Screenshot 2023-11-06 at 12 00 50


Now I enable Faust but I'm not checking any setting:

I can see the following in the GraphQL Query:

Screenshot 2023-11-06 at 12 07 31


All `src` attributes have been re-writen to point to Headless URL. 

**This the expected behaviour when no setting has been enabled** 

Since we have specifically the **Use the WordPress domain for media URLs in post content** setting to rewrite those links back:

Screenshot 2023-11-06 at 12 11 12

When I enable this setting then I get back the original src:

Screenshot 2023-11-06 at 12 10 44

Now we create a new post  with Faust Enabled and link in any post content to an item in the media library. We observe the same behaviour when `Use the WordPress domain for media URLs in post content` is checked.

Some observations:

It seems that the changes only affect `src` and `href` attributes but not `srcset` attributes:

The `editorBlocks` attributes are un-nafected and they always point to the original WP URL because the wp-content-blocks plugin only looks at the contents of the database using [get_post](https://developer.wordpress.org/reference/functions/get_post/) and [parse_blocks](https://developer.wordpress.org/reference/functions/parse_blocks/)

Is this what we want to be?

**Comment by mindctrl** [comment]
Here's the setup I've been using to test:

## Active plugins
- Classic Editor 1.6.3
- Faust.js (git)
- Query Monitor 3.14.1
- WPGraphQL 1.1.8.0
- WPGraphQL Content Blocks 2.0.0

## Post content
### Post ID 45
```
<!-- wp:paragraph -->
<p><a href="http://rewrites.local/hello-world/" data-type="post" data-id="1">Link</a></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><a href="http://rewrites.local/sample-page/" data-type="page" data-id="2">Another link</a></p>
<!-- /wp:paragraph -->

<!-- wp:image {"id":15,"sizeSlug":"large","linkDestination":"none"} -->
<figure class="wp-block-image size-large"><img src="http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-1024x768.jpg" alt="" class="wp-image-15"/></figure>
<!-- /wp:image -->
```

### Post ID 41
```
<a href="http://rewrites.local/hello-world/">link</a>

<a href="http://rewrites.local/hello-world/">thing</a>

pdf

<a href="http://rewrites.local/sample-page/">sample</a>
```

### Post ID 39
```
<!-- wp:paragraph -->
<p><a href="http://rewrites.local/hello-world/" data-type="post" data-id="1">Hello world</a></p>
<!-- /wp:paragraph -->
```

### Post ID 34
```
<!-- wp:paragraph -->
<p>This post has a featured image.</p>
<!-- /wp:paragraph -->
```

### Post meta for post ID 34
```
`_thumnail_id: 15`
```

`guid` for Post ID 15, which is the featured image for Post 34
`http://rewrites.local/wp-content/uploads/2023/10/IMG_8963.jpg`

## Query used for all tests
```
query NewQuery {
  posts(first: 4) {
    nodes {
      databaseId
      content
      editorBlocks {
        ... on CoreParagraph {
          attributes {
            content
          }
        }
        ... on CoreImage {
          attributes {
            url
            src
          }
          mediaDetails {
            sizes {
              sourceUrl
            }
          }
        }
      }
    }
  }
}
```

## Results on canary branch
#### 1. Post/Cat/Image pointing to WP
- Enable Post and Category URL rewrites (OFF)
- Use the WordPress domain for media URLs in post content (ON)
##### Response
```
{
  "data": {
    "posts": {
      "nodes": [
        {
          "databaseId": 45,
          "content": "\n<p><a href=\"http://rewrites.local/hello-world/\" data-type=\"post\" data-id=\"1\">Link</a></p>\n\n\n\n<p><a href=\"http://rewrites.local/sample-page/\" data-type=\"page\" data-id=\"2\">Another link</a></p>\n\n\n\n<figure class=\"wp-block-image size-large\"><img decoding=\"async\" loading=\"lazy\" width=\"1024\" height=\"768\" src=\"http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-1024x768.jpg\" alt=\"\" class=\"wp-image-15\" srcset=\"http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-1024x768.jpg 1024w, http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-300x225.jpg 300w, http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-768x576.jpg 768w, http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-1536x1152.jpg 1536w, http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-2048x1536.jpg 2048w\" sizes=\"(max-width: 1024px) 100vw, 1024px\" /></figure>\n",
          "editorBlocks": [
            {
              "attributes": {
                "content": "<a href=\"http://rewrites.local/hello-world/\" data-type=\"post\" data-id=\"1\">Link</a>"
              }
            },
            {
              "attributes": {
                "content": "<a href=\"http://rewrites.local/sample-page/\" data-type=\"page\" data-id=\"2\">Another link</a>"
              }
            },
            {
              "attributes": {
                "url": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-1024x768.jpg",
                "src": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-1024x768.jpg"
              },
              "mediaDetails": {
                "sizes": [
                  {
                    "sourceUrl": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-300x225.jpg"
                  },
                  {
                    "sourceUrl": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-1024x768.jpg"
                  },
                  {
                    "sourceUrl": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-150x150.jpg"
                  },
                  {
                    "sourceUrl": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-768x576.jpg"
                  },
                  {
                    "sourceUrl": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-1536x1152.jpg"
                  },
                  {
                    "sourceUrl": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-2048x1536.jpg"
                  }
                ]
              }
            }
          ]
        },
        {
          "databaseId": 41,
          "content": "<p><a href=\"http://rewrites.local/hello-world/\">link</a></p>\n<p><a href=\"http://rewrites.local/hello-world/\">thing</a></p>\n<p>pdf</p>\n<p><a href=\"http://rewrites.local/sample-page/\">sample</a></p>\n",
          "editorBlocks": [
            {}
          ]
        },
        {
          "databaseId": 39,
          "content": "\n<p><a href=\"http://rewrites.local/hello-world/\" data-type=\"post\" data-id=\"1\">Hello world</a></p>\n",
          "editorBlocks": [
            {
              "attributes": {
                "content": "<a href=\"http://rewrites.local/hello-world/\" data-type=\"post\" data-id=\"1\">Hello world</a>"
              }
            }
          ]
        },
        {
          "databaseId": 34,
          "content": "\n<p>This post has a featured image.</p>\n",
          "editorBlocks": [
            {
              "attributes": {
                "content": "This post has a featured image."
              }
            }
          ]
        }
      ]
    }
  },
  "extensions": {
    "debug": [
      {
        "type": "DEBUG_LOGS_INACTIVE",
        "message": "GraphQL Debug logging is not active. To see debug logs, GRAPHQL_DEBUG must be enabled."
      }
    ]
  }
}
```

#### 2. Post/Cat/Image pointing to Front-end site URL
- Enable Post and Category URL rewrites (ON)
- Use the WordPress domain for media URLS in post content (OFF)

##### Response
```
{
  "data": {
    "posts": {
      "nodes": [
        {
          "databaseId": 45,
          "content": "\n<p><a href=\"http://localhost:3000/hello-world/\" data-type=\"post\" data-id=\"1\">Link</a></p>\n\n\n\n<p><a href=\"http://localhost:3000/sample-page/\" data-type=\"page\" data-id=\"2\">Another link</a></p>\n\n\n\n<figure class=\"wp-block-image size-large\"><img decoding=\"async\" loading=\"lazy\" width=\"1024\" height=\"768\" src=\"http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-1024x768.jpg\" alt=\"\" class=\"wp-image-15\" srcset=\"http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-1024x768.jpg 1024w, http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-300x225.jpg 300w, http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-768x576.jpg 768w, http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-1536x1152.jpg 1536w, http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-2048x1536.jpg 2048w\" sizes=\"(max-width: 1024px) 100vw, 1024px\" /></figure>\n",
          "editorBlocks": [
            {
              "attributes": {
                "content": "<a href=\"http://rewrites.local/hello-world/\" data-type=\"post\" data-id=\"1\">Link</a>"
              }
            },
            {
              "attributes": {
                "content": "<a href=\"http://rewrites.local/sample-page/\" data-type=\"page\" data-id=\"2\">Another link</a>"
              }
            },
            {
              "attributes": {
                "url": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-1024x768.jpg",
                "src": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-1024x768.jpg"
              },
              "mediaDetails": {
                "sizes": [
                  {
                    "sourceUrl": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-300x225.jpg"
                  },
                  {
                    "sourceUrl": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-1024x768.jpg"
                  },
                  {
                    "sourceUrl": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-150x150.jpg"
                  },
                  {
                    "sourceUrl": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-768x576.jpg"
                  },
                  {
                    "sourceUrl": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-1536x1152.jpg"
                  },
                  {
                    "sourceUrl": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-2048x1536.jpg"
                  }
                ]
              }
            }
          ]
        },
        {
          "databaseId": 41,
          "content": "<p><a href=\"http://localhost:3000/hello-world/\">link</a></p>\n<p><a href=\"http://localhost:3000/hello-world/\">thing</a></p>\n<p>pdf</p>\n<p><a href=\"http://localhost:3000/sample-page/\">sample</a></p>\n",
          "editorBlocks": [
            {}
          ]
        },
        {
          "databaseId": 39,
          "content": "\n<p><a href=\"http://localhost:3000/hello-world/\" data-type=\"post\" data-id=\"1\">Hello world</a></p>\n",
          "editorBlocks": [
            {
              "attributes": {
                "content": "<a href=\"http://rewrites.local/hello-world/\" data-type=\"post\" data-id=\"1\">Hello world</a>"
              }
            }
          ]
        },
        {
          "databaseId": 34,
          "content": "\n<p>This post has a featured image.</p>\n",
          "editorBlocks": [
            {
              "attributes": {
                "content": "This post has a featured image."
              }
            }
          ]
        }
      ]
    }
  },
  "extensions": {
    "debug": [
      {
        "type": "DEBUG_LOGS_INACTIVE",
        "message": "GraphQL Debug logging is not active. To see debug logs, GRAPHQL_DEBUG must be enabled."
      }
    ]
  }
}
```




#### 3. Post/Cat/ pointing to Front-end, Image pointing to WP
- Enable Post and Category URL rewrites (ON)
- Use the WordPress domain for media URLS in post content (ON)

##### Response
```
{
  "data": {
    "posts": {
      "nodes": [
        {
          "databaseId": 45,
          "content": "\n<p><a href=\"http://localhost:3000/hello-world/\" data-type=\"post\" data-id=\"1\">Link</a></p>\n\n\n\n<p><a href=\"http://localhost:3000/sample-page/\" data-type=\"page\" data-id=\"2\">Another link</a></p>\n\n\n\n<figure class=\"wp-block-image size-large\"><img decoding=\"async\" loading=\"lazy\" width=\"1024\" height=\"768\" src=\"http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-1024x768.jpg\" alt=\"\" class=\"wp-image-15\" srcset=\"http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-1024x768.jpg 1024w, http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-300x225.jpg 300w, http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-768x576.jpg 768w, http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-1536x1152.jpg 1536w, http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-2048x1536.jpg 2048w\" sizes=\"(max-width: 1024px) 100vw, 1024px\" /></figure>\n",
          "editorBlocks": [
            {
              "attributes": {
                "content": "<a href=\"http://rewrites.local/hello-world/\" data-type=\"post\" data-id=\"1\">Link</a>"
              }
            },
            {
              "attributes": {
                "content": "<a href=\"http://rewrites.local/sample-page/\" data-type=\"page\" data-id=\"2\">Another link</a>"
              }
            },
            {
              "attributes": {
                "url": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-1024x768.jpg",
                "src": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-1024x768.jpg"
              },
              "mediaDetails": {
                "sizes": [
                  {
                    "sourceUrl": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-300x225.jpg"
                  },
                  {
                    "sourceUrl": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-1024x768.jpg"
                  },
                  {
                    "sourceUrl": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-150x150.jpg"
                  },
                  {
                    "sourceUrl": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-768x576.jpg"
                  },
                  {
                    "sourceUrl": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-1536x1152.jpg"
                  },
                  {
                    "sourceUrl": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-2048x1536.jpg"
                  }
                ]
              }
            }
          ]
        },
        {
          "databaseId": 41,
          "content": "<p><a href=\"http://localhost:3000/hello-world/\">link</a></p>\n<p><a href=\"http://localhost:3000/hello-world/\">thing</a></p>\n<p>pdf</p>\n<p><a href=\"http://localhost:3000/sample-page/\">sample</a></p>\n",
          "editorBlocks": [
            {}
          ]
        },
        {
          "databaseId": 39,
          "content": "\n<p><a href=\"http://localhost:3000/hello-world/\" data-type=\"post\" data-id=\"1\">Hello world</a></p>\n",
          "editorBlocks": [
            {
              "attributes": {
                "content": "<a href=\"http://rewrites.local/hello-world/\" data-type=\"post\" data-id=\"1\">Hello world</a>"
              }
            }
          ]
        },
        {
          "databaseId": 34,
          "content": "\n<p>This post has a featured image.</p>\n",
          "editorBlocks": [
            {
              "attributes": {
                "content": "This post has a featured image."
              }
            }
          ]
        }
      ]
    }
  },
  "extensions": {
    "debug": [
      {
        "type": "DEBUG_LOGS_INACTIVE",
        "message": "GraphQL Debug logging is not active. To see debug logs, GRAPHQL_DEBUG must be enabled."
      }
    ]
  }
}
```


#### 4. Post/Cat/ pointing to WP, Image pointing to Front-end URL
- Enable Post and Category URL rewrites (OFF)
- Use the WordPress domain for media URLS in post content (OFF)

##### Response
```
{
  "data": {
    "posts": {
      "nodes": [
        {
          "databaseId": 45,
          "content": "\n<p><a href=\"http://rewrites.local/hello-world/\" data-type=\"post\" data-id=\"1\">Link</a></p>\n\n\n\n<p><a href=\"http://rewrites.local/sample-page/\" data-type=\"page\" data-id=\"2\">Another link</a></p>\n\n\n\n<figure class=\"wp-block-image size-large\"><img decoding=\"async\" loading=\"lazy\" width=\"1024\" height=\"768\" src=\"http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-1024x768.jpg\" alt=\"\" class=\"wp-image-15\" srcset=\"http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-1024x768.jpg 1024w, http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-300x225.jpg 300w, http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-768x576.jpg 768w, http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-1536x1152.jpg 1536w, http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-2048x1536.jpg 2048w\" sizes=\"(max-width: 1024px) 100vw, 1024px\" /></figure>\n",
          "editorBlocks": [
            {
              "attributes": {
                "content": "<a href=\"http://rewrites.local/hello-world/\" data-type=\"post\" data-id=\"1\">Link</a>"
              }
            },
            {
              "attributes": {
                "content": "<a href=\"http://rewrites.local/sample-page/\" data-type=\"page\" data-id=\"2\">Another link</a>"
              }
            },
            {
              "attributes": {
                "url": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-1024x768.jpg",
                "src": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-1024x768.jpg"
              },
              "mediaDetails": {
                "sizes": [
                  {
                    "sourceUrl": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-300x225.jpg"
                  },
                  {
                    "sourceUrl": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-1024x768.jpg"
                  },
                  {
                    "sourceUrl": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-150x150.jpg"
                  },
                  {
                    "sourceUrl": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-768x576.jpg"
                  },
                  {
                    "sourceUrl": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-1536x1152.jpg"
                  },
                  {
                    "sourceUrl": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-2048x1536.jpg"
                  }
                ]
              }
            }
          ]
        },
        {
          "databaseId": 41,
          "content": "<p><a href=\"http://rewrites.local/hello-world/\">link</a></p>\n<p><a href=\"http://rewrites.local/hello-world/\">thing</a></p>\n<p>pdf</p>\n<p><a href=\"http://rewrites.local/sample-page/\">sample</a></p>\n",
          "editorBlocks": [
            {}
          ]
        },
        {
          "databaseId": 39,
          "content": "\n<p><a href=\"http://rewrites.local/hello-world/\" data-type=\"post\" data-id=\"1\">Hello world</a></p>\n",
          "editorBlocks": [
            {
              "attributes": {
                "content": "<a href=\"http://rewrites.local/hello-world/\" data-type=\"post\" data-id=\"1\">Hello world</a>"
              }
            }
          ]
        },
        {
          "databaseId": 34,
          "content": "\n<p>This post has a featured image.</p>\n",
          "editorBlocks": [
            {
              "attributes": {
                "content": "This post has a featured image."
              }
            }
          ]
        }
      ]
    }
  },
  "extensions": {
    "debug": [
      {
        "type": "DEBUG_LOGS_INACTIVE",
        "message": "GraphQL Debug logging is not active. To see debug logs, GRAPHQL_DEBUG must be enabled."
      }
    ]
  }
}
```



## Results on this PR branch
#### 1. Post/Cat/Image pointing to WP
- Enable Post and Category URL rewrites (OFF)
- Use the WordPress domain for media URLs in post content (ON)
##### Response
```
{
  "data": {
    "posts": {
      "nodes": [
        {
          "databaseId": 45,
          "content": "\n<p><a href=\"http://rewrites.local/hello-world/\" data-type=\"post\" data-id=\"1\">Link</a></p>\n\n\n\n<p><a href=\"http://rewrites.local/sample-page/\" data-type=\"page\" data-id=\"2\">Another link</a></p>\n\n\n\n<figure class=\"wp-block-image size-large\"><img decoding=\"async\" loading=\"lazy\" width=\"1024\" height=\"768\" src=\"http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-1024x768.jpg\" alt=\"\" class=\"wp-image-15\" srcset=\"http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-1024x768.jpg 1024w, http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-300x225.jpg 300w, http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-768x576.jpg 768w, http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-1536x1152.jpg 1536w, http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-2048x1536.jpg 2048w\" sizes=\"(max-width: 1024px) 100vw, 1024px\" /></figure>\n",
          "editorBlocks": [
            {
              "attributes": {
                "content": "<a href=\"http://rewrites.local/hello-world/\" data-type=\"post\" data-id=\"1\">Link</a>"
              }
            },
            {
              "attributes": {
                "content": "<a href=\"http://rewrites.local/sample-page/\" data-type=\"page\" data-id=\"2\">Another link</a>"
              }
            },
            {
              "attributes": {
                "url": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-1024x768.jpg",
                "src": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-1024x768.jpg"
              },
              "mediaDetails": {
                "sizes": [
                  {
                    "sourceUrl": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-300x225.jpg"
                  },
                  {
                    "sourceUrl": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-1024x768.jpg"
                  },
                  {
                    "sourceUrl": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-150x150.jpg"
                  },
                  {
                    "sourceUrl": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-768x576.jpg"
                  },
                  {
                    "sourceUrl": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-1536x1152.jpg"
                  },
                  {
                    "sourceUrl": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-2048x1536.jpg"
                  }
                ]
              }
            }
          ]
        },
        {
          "databaseId": 41,
          "content": "<p><a href=\"http://rewrites.local/hello-world/\">link</a></p>\n<p><a href=\"http://rewrites.local/hello-world/\">thing</a></p>\n<p>pdf</p>\n<p><a href=\"http://rewrites.local/sample-page/\">sample</a></p>\n",
          "editorBlocks": [
            {}
          ]
        },
        {
          "databaseId": 39,
          "content": "\n<p><a href=\"http://rewrites.local/hello-world/\" data-type=\"post\" data-id=\"1\">Hello world</a></p>\n",
          "editorBlocks": [
            {
              "attributes": {
                "content": "<a href=\"http://rewrites.local/hello-world/\" data-type=\"post\" data-id=\"1\">Hello world</a>"
              }
            }
          ]
        },
        {
          "databaseId": 34,
          "content": "\n<p>This post has a featured image.</p>\n",
          "editorBlocks": [
            {
              "attributes": {
                "content": "This post has a featured image."
              }
            }
          ]
        }
      ]
    }
  },
  "extensions": {
    "debug": [
      {
        "type": "DEBUG_LOGS_INACTIVE",
        "message": "GraphQL Debug logging is not active. To see debug logs, GRAPHQL_DEBUG must be enabled."
      }
    ]
  }
}
```

#### 2. Post/Cat/Image pointing to Front-end site URL
- Enable Post and Category URL rewrites (ON)
- Use the WordPress domain for media URLS in post content (OFF)

##### Response
```
{
  "data": {
    "posts": {
      "nodes": [
        {
          "databaseId": 45,
          "content": "\n<p><a href=\"http://localhost:3000/hello-world/\" data-type=\"post\" data-id=\"1\">Link</a></p>\n\n\n\n<p><a href=\"http://localhost:3000/sample-page/\" data-type=\"page\" data-id=\"2\">Another link</a></p>\n\n\n\n<figure class=\"wp-block-image size-large\"><img decoding=\"async\" loading=\"lazy\" width=\"1024\" height=\"768\" src=\"http://localhost:3000/wp-content/uploads/2023/10/IMG_8963-1024x768.jpg\" alt=\"\" class=\"wp-image-15\" srcset=\"http://localhost:3000/wp-content/uploads/2023/10/IMG_8963-1024x768.jpg 1024w, http://localhost:3000/wp-content/uploads/2023/10/IMG_8963-300x225.jpg 300w, http://localhost:3000/wp-content/uploads/2023/10/IMG_8963-768x576.jpg 768w, http://localhost:3000/wp-content/uploads/2023/10/IMG_8963-1536x1152.jpg 1536w, http://localhost:3000/wp-content/uploads/2023/10/IMG_8963-2048x1536.jpg 2048w\" sizes=\"(max-width: 1024px) 100vw, 1024px\" /></figure>\n",
          "editorBlocks": [
            {
              "attributes": {
                "content": "<a href=\"http://localhost:3000/hello-world/\" data-type=\"post\" data-id=\"1\">Link</a>"
              }
            },
            {
              "attributes": {
                "content": "<a href=\"http://localhost:3000/sample-page/\" data-type=\"page\" data-id=\"2\">Another link</a>"
              }
            },
            {
              "attributes": {
                "url": "http://localhost:3000/wp-content/uploads/2023/10/IMG_8963-1024x768.jpg",
                "src": "http://localhost:3000/wp-content/uploads/2023/10/IMG_8963-1024x768.jpg"
              },
              "mediaDetails": {
                "sizes": [
                  {
                    "sourceUrl": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-300x225.jpg"
                  },
                  {
                    "sourceUrl": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-1024x768.jpg"
                  },
                  {
                    "sourceUrl": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-150x150.jpg"
                  },
                  {
                    "sourceUrl": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-768x576.jpg"
                  },
                  {
                    "sourceUrl": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-1536x1152.jpg"
                  },
                  {
                    "sourceUrl": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-2048x1536.jpg"
                  }
                ]
              }
            }
          ]
        },
        {
          "databaseId": 41,
          "content": "<p><a href=\"http://localhost:3000/hello-world/\">link</a></p>\n<p><a href=\"http://localhost:3000/hello-world/\">thing</a></p>\n<p>pdf</p>\n<p><a href=\"http://localhost:3000/sample-page/\">sample</a></p>\n",
          "editorBlocks": [
            {}
          ]
        },
        {
          "databaseId": 39,
          "content": "\n<p><a href=\"http://localhost:3000/hello-world/\" data-type=\"post\" data-id=\"1\">Hello world</a></p>\n",
          "editorBlocks": [
            {
              "attributes": {
                "content": "<a href=\"http://localhost:3000/hello-world/\" data-type=\"post\" data-id=\"1\">Hello world</a>"
              }
            }
          ]
        },
        {
          "databaseId": 34,
          "content": "\n<p>This post has a featured image.</p>\n",
          "editorBlocks": [
            {
              "attributes": {
                "content": "This post has a featured image."
              }
            }
          ]
        }
      ]
    }
  },
  "extensions": {
    "debug": [
      {
        "type": "DEBUG_LOGS_INACTIVE",
        "message": "GraphQL Debug logging is not active. To see debug logs, GRAPHQL_DEBUG must be enabled."
      }
    ]
  }
}
```




#### 3. Post/Cat/ pointing to Front-end, Image pointing to WP
- Enable Post and Category URL rewrites (ON)
- Use the WordPress domain for media URLS in post content (ON)

##### Response
```
{
  "data": {
    "posts": {
      "nodes": [
        {
          "databaseId": 45,
          "content": "\n<p><a href=\"http://localhost:3000/hello-world/\" data-type=\"post\" data-id=\"1\">Link</a></p>\n\n\n\n<p><a href=\"http://localhost:3000/sample-page/\" data-type=\"page\" data-id=\"2\">Another link</a></p>\n\n\n\n<figure class=\"wp-block-image size-large\"><img decoding=\"async\" loading=\"lazy\" width=\"1024\" height=\"768\" src=\"http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-1024x768.jpg\" alt=\"\" class=\"wp-image-15\" srcset=\"http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-1024x768.jpg 1024w, http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-300x225.jpg 300w, http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-768x576.jpg 768w, http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-1536x1152.jpg 1536w, http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-2048x1536.jpg 2048w\" sizes=\"(max-width: 1024px) 100vw, 1024px\" /></figure>\n",
          "editorBlocks": [
            {
              "attributes": {
                "content": "<a href=\"http://localhost:3000/hello-world/\" data-type=\"post\" data-id=\"1\">Link</a>"
              }
            },
            {
              "attributes": {
                "content": "<a href=\"http://localhost:3000/sample-page/\" data-type=\"page\" data-id=\"2\">Another link</a>"
              }
            },
            {
              "attributes": {
                "url": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-1024x768.jpg",
                "src": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-1024x768.jpg"
              },
              "mediaDetails": {
                "sizes": [
                  {
                    "sourceUrl": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-300x225.jpg"
                  },
                  {
                    "sourceUrl": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-1024x768.jpg"
                  },
                  {
                    "sourceUrl": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-150x150.jpg"
                  },
                  {
                    "sourceUrl": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-768x576.jpg"
                  },
                  {
                    "sourceUrl": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-1536x1152.jpg"
                  },
                  {
                    "sourceUrl": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-2048x1536.jpg"
                  }
                ]
              }
            }
          ]
        },
        {
          "databaseId": 41,
          "content": "<p><a href=\"http://localhost:3000/hello-world/\">link</a></p>\n<p><a href=\"http://localhost:3000/hello-world/\">thing</a></p>\n<p>pdf</p>\n<p><a href=\"http://localhost:3000/sample-page/\">sample</a></p>\n",
          "editorBlocks": [
            {}
          ]
        },
        {
          "databaseId": 39,
          "content": "\n<p><a href=\"http://localhost:3000/hello-world/\" data-type=\"post\" data-id=\"1\">Hello world</a></p>\n",
          "editorBlocks": [
            {
              "attributes": {
                "content": "<a href=\"http://localhost:3000/hello-world/\" data-type=\"post\" data-id=\"1\">Hello world</a>"
              }
            }
          ]
        },
        {
          "databaseId": 34,
          "content": "\n<p>This post has a featured image.</p>\n",
          "editorBlocks": [
            {
              "attributes": {
                "content": "This post has a featured image."
              }
            }
          ]
        }
      ]
    }
  },
  "extensions": {
    "debug": [
      {
        "type": "DEBUG_LOGS_INACTIVE",
        "message": "GraphQL Debug logging is not active. To see debug logs, GRAPHQL_DEBUG must be enabled."
      }
    ]
  }
}
```


#### 4. Post/Cat/ pointing to WP, Image pointing to Front-end URL
- Enable Post and Category URL rewrites (OFF)
- Use the WordPress domain for media URLS in post content (OFF)

##### Response
```
{
  "data": {
    "posts": {
      "nodes": [
        {
          "databaseId": 45,
          "content": "\n<p><a href=\"http://rewrites.local/hello-world/\" data-type=\"post\" data-id=\"1\">Link</a></p>\n\n\n\n<p><a href=\"http://rewrites.local/sample-page/\" data-type=\"page\" data-id=\"2\">Another link</a></p>\n\n\n\n<figure class=\"wp-block-image size-large\"><img decoding=\"async\" loading=\"lazy\" width=\"1024\" height=\"768\" src=\"http://localhost:3000/wp-content/uploads/2023/10/IMG_8963-1024x768.jpg\" alt=\"\" class=\"wp-image-15\" srcset=\"http://localhost:3000/wp-content/uploads/2023/10/IMG_8963-1024x768.jpg 1024w, http://localhost:3000/wp-content/uploads/2023/10/IMG_8963-300x225.jpg 300w, http://localhost:3000/wp-content/uploads/2023/10/IMG_8963-768x576.jpg 768w, http://localhost:3000/wp-content/uploads/2023/10/IMG_8963-1536x1152.jpg 1536w, http://localhost:3000/wp-content/uploads/2023/10/IMG_8963-2048x1536.jpg 2048w\" sizes=\"(max-width: 1024px) 100vw, 1024px\" /></figure>\n",
          "editorBlocks": [
            {
              "attributes": {
                "content": "<a href=\"http://rewrites.local/hello-world/\" data-type=\"post\" data-id=\"1\">Link</a>"
              }
            },
            {
              "attributes": {
                "content": "<a href=\"http://rewrites.local/sample-page/\" data-type=\"page\" data-id=\"2\">Another link</a>"
              }
            },
            {
              "attributes": {
                "url": "http://localhost:3000/wp-content/uploads/2023/10/IMG_8963-1024x768.jpg",
                "src": "http://localhost:3000/wp-content/uploads/2023/10/IMG_8963-1024x768.jpg"
              },
              "mediaDetails": {
                "sizes": [
                  {
                    "sourceUrl": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-300x225.jpg"
                  },
                  {
                    "sourceUrl": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-1024x768.jpg"
                  },
                  {
                    "sourceUrl": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-150x150.jpg"
                  },
                  {
                    "sourceUrl": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-768x576.jpg"
                  },
                  {
                    "sourceUrl": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-1536x1152.jpg"
                  },
                  {
                    "sourceUrl": "http://rewrites.local/wp-content/uploads/2023/10/IMG_8963-2048x1536.jpg"
                  }
                ]
              }
            }
          ]
        },
        {
          "databaseId": 41,
          "content": "<p><a href=\"http://rewrites.local/hello-world/\">link</a></p>\n<p><a href=\"http://rewrites.local/hello-world/\">thing</a></p>\n<p>pdf</p>\n<p><a href=\"http://rewrites.local/sample-page/\">sample</a></p>\n",
          "editorBlocks": [
            {}
          ]
        },
        {
          "databaseId": 39,
          "content": "\n<p><a href=\"http://rewrites.local/hello-world/\" data-type=\"post\" data-id=\"1\">Hello world</a></p>\n",
          "editorBlocks": [
            {
              "attributes": {
                "content": "<a href=\"http://rewrites.local/hello-world/\" data-type=\"post\" data-id=\"1\">Hello world</a>"
              }
            }
          ]
        },
        {
          "databaseId": 34,
          "content": "\n<p>This post has a featured image.</p>\n",
          "editorBlocks": [
            {
              "attributes": {
                "content": "This post has a featured image."
              }
            }
          ]
        }
      ]
    }
  },
  "extensions": {
    "debug": [
      {
        "type": "DEBUG_LOGS_INACTIVE",
        "message": "GraphQL Debug logging is not active. To see debug logs, GRAPHQL_DEBUG must be enabled."
      }
    ]
  }
}
```

**Comment by mindctrl** [comment]
[merl-1228-diffs.zip](https://github.com/wpengine/faustjs/files/13280836/merl-1228-diffs.zip)

zip of the result diffs posted above.

**Comment by theodesp** [comment]
@mindctrl that should be OK will check again today and approve. Thanks.

**Review by theodesp — DISMISSED** [review]
LGTM! It would be nice to get more approvals.

**Comment by TeresaGobble** [comment]
Hi John! You've done an awesome job explaining your test flow and helping me understand the results- thank you so much for your efforts. 💪 

I have two questions on the results I'm seeing. I've documented my testing results in a slideshow so I can compare sections a little more readily to test my understanding. Would you please take a look at the two comments I have in the slides [here](https://docs.google.com/presentation/d/1gd9hgxc9pL24k9Mv1n4AKhIoKR-nUD6I2Kep5mXqveQ/edit?usp=sharing) and let me know your thoughts?

File: plugins/faustwp/includes/replacement/callbacks.php (hunk 2 above)
Comment (mindctrl) [reply plugins/faustwp/includes/replacement/callbacks.php]: I restored this and updated the internal logic to fix some issues that already existed in canary.

**Review by theodesp — APPROVED** [review]
